### ISSUE TITLE
xblas "problem"

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-linkchecker#26]
```
Homepage link http://www.netlib.org/xblas/ is dead (Connect timeout (60 seconds)) for more than a month 
and should be replaced by alive link (or link to archive.org as a last resort).
```

It seems to resolve fine.  Will that error clear up eventually?

**Comment by jrmarino** [comment]
this one too:

```
Homepage link https://www.netlib.org/lapack/ is dead (DNS error: timeout while contacting DNS servers) for more than a month
and should be replaced by alive link (or link to archive.org as a last resort).
```

**Comment by AMDmi3** [comment]
https://downforeveryoneorjustme.com/netlib.org?proto=http&www=1
![1](https://user-images.githubusercontent.com/474217/98706100-7da20e00-238f-11eb-86b9-2858640072ed.png)

**Comment by jrmarino** [comment]
![image](https://user-images.githubusercontent.com/1125622/98707327-879f1f00-2345-11eb-9690-6e595d733b4c.png)

**Comment by jrmarino** [comment]
![image](https://user-images.githubusercontent.com/1125622/98710924-e49cd400-2349-11eb-940f-d8add7339bc2.png)

**Comment by jrmarino** [comment]
please reopen?

**Comment by AMDmi3** [comment]
Well it's still down from all my locations, confirmed by downforeveryoneorjustme.com, so no.

**Comment by jrmarino** [comment]
how does downforeveryoneorjustme.com give different answers? a few seconds ago:
![image](https://user-images.githubusercontent.com/1125622/98724939-1453d800-235a-11eb-9547-7bff9cd599db.png)

**Comment by jrmarino** [comment]
And I can get to pages.  Something is amiss.  I can believe you can't get it from some locations but wouldn't the downforeveryone site give the same results for everyone in the world?

**Comment by AMDmi3** [comment]
No idea regarding downforeveryone. Regadless, we've already discussed this - as long as it's reliably broken from any location, it's broken.

**Comment by jrmarino** [comment]
Can you please reinvestigate this?  The site says DNS failed all checks (latest 1 day ago) but uptrends is showing all green, all sites.  The check you use seems to be broken.
![image](https://user-images.githubusercontent.com/1125622/101926582-f9fb5d00-3b98-11eb-8ccc-8fa713517a59.png)

**Comment by AMDmi3** [comment]
Nothing has changed, it's dead from 4 my locations. It may be that University of Tennessee (utk.edu) which owns the host is blocking all traffic from Russia.

**Comment by jrmarino** [comment]
okay, I get that may be the cause, but your criteria is that if the site isn't available from anywhere, it's a valid problem.  Your problem report refers to "uptrends" as a credible checking site which shows it is available from everywhere, so by that criteria xblas and friends should not be on the problem report.

Related, "norm" is available just able everywhere, but the 4 places uptrends marks as issue includes beijing and hong kong.  Given that norm comes from US military site, this could be a govt directed block.  Now I appreciate that kind of detection is hard from your side, but it begs the question: How can the owner fix issues of active blocking?  It's completely out of their control.  So how do these problems get resolved if intentional blocking is the problem?

**Comment by AMDmi3** [comment]
>  Your problem report refers to "uptrends" as a credible checking site

It does not refer to it "as a credible checking site" at all. It just refers to it.

> So how do these problems get resolved if intentional blocking is the problem?

There's nothing wrong for them to not get resolved if they can't be. It makes sense to write upstream and notify them about the problem though, and I'd provide alternative link to archive.org in the package (this won't solve the problem though as it doesn't make sense to remove official link).

**Comment by jrmarino** [comment]
I have a different opinion on this.
I would call marking something as a problem when nobody can reproduce it as a "false positive".
If I would contact the netlib people and say they have a website problem (even referring to repology) I would get laughed at as a fool, especially if they checked it with sites such as uptrend and no issue can be detected.

Please consider having a white list for false positives like this (or fix the detection issue)
I hope you will not say "This is not a false positive" because I don't see how it can be called anything else.
I'm trying to work within your strict rules here, but I don't see any chance for success here because it appears repology is just plain wrong.  Is there any 3rd party site that supports the assertion that there is a problem with netlib?  If there is, I'll be happy to investigate further.

**Comment by AMDmi3** [comment]
> I would call marking something as a problem when nobody can reproduce it as a "false positive".

Nobody != you, especially if you haven't tried. There are hundreds of website checkers, find any with presence in Russia. Took me ~10 seconds to find: https://www.sitestatus.ru/?url=netlib.org

**Comment by jrmarino** [comment]
alright.
So the bar was stated as "it's broken if it doesn't work everywhere" but apparently it's more accurate to say "the site is considered broken if it's not accessible from Russia" (yes, I know the second statement doesn't invalidate the first)
I have a VPN but unfortunately it does not have any servers located in Russia.
Do you have any suggestions to determine exactly where the connectivity is broken from Russia?  maybe some diagnostic site that always confirms the "problem" repology reports?
I'm no network expert so other than a severed cable or misconfigured telecom traffic router, I don't know how to diagnose "accessible in all uptrends server locations but not Russia" problem.
If it's something the owners of netlib.org can fix, I'd love to inform them.

**Comment by AMDmi3** [comment]
Inform them that their site is not accessible from Russia. I'm not wasting any more time on this.
