### ISSUE TITLE
repology-linkchecker is hammering the buildd.debian.org website

### ISSUE THREAD

**Issue by aurel32** [repology/repology-linkchecker#27]
Since 2021-03-07, repology-linkchecker is hammering buildd.debian.org, it seems to access pages for individual packages. I am not sure which information repology-linkchecker is looking for, but it seems to me that this is completely inefficient on both side.

If I understand correctly, repology wants to know the version of each package in Debian. In that case parsing the Sources and Packages files from the APT repositories seems to be a better way to do it.

**Comment by AMDmi3** [comment]
Linkchecker is just checking availability of links associated with the packages.

There was a huge change recently: before, we only had links which come from packages themselves, e.g. contents of `Homepage` field from Debian Packages/Sources files. After the change, a huge amount of links generated for each package from templates 

https://github.com/repology/repology-updater/blob/3921d9cae39d6c9f23018f51539aa5f08f8a7fbc/repos.d/deb/debian.yaml#L65-L75

were materialized and link checker began crunching through them as well. I admit that this is pointless for most of them, however I haven't yet came with the solution on how to outline the subset of links which do require checking, and also I wanted to check each link at least once to make sure that templates are correct for all cases.

Does this generate excess load on buildd.debian.org? The link checker tries to be polite, doing 3 second delays between requests. The recheck period is also quite big (2-3 weeks) so after it checks all generated links for the first time the rate will go down.

Can increase delay between requests right away, or can disable checking for this host if it's critical. If it's not I'll still disable it but need 1-2 weeks for a complete solution.

**Comment by aurel32** [comment]
Yes, this causes an increased load on buildd.debian.org, repology-linkchecker now accounts for around 60% of the requests to this server. This would be nice if this can be reduced by an order of magnitude. We can probably increase the resources of this server, but we do not see the point if 60% of the resources are used by a single user, for something that doesn't seems to be really useful.

**Comment by AMDmi3** [comment]
I've limited linkchecker to 1 request per minute for now, hope that solves the problem. As mentioned, when I improve handling for generated links, there probably won't be any requests at all.
