### ISSUE TITLE
systematic issue with sourceforge projects

### ISSUE THREAD

**Issue by jrmarino** [repology/repology-linkchecker#34]
There quite a few issues with false negatives in the Ravenport's "problems" link.  This report is going to focus on one of them, sourceforge project pages.

Something is wrong with the linkchecker or the infrastructure.  All the reported issues on sourceforge are bogus, e.g.:

- Homepage link https://sourceforge.net/projects/extremetuxracer/ is [dead](https://repology.org/link/https://sourceforge.net/projects/extremetuxracer/) (Connect timeout (60 seconds))
- Homepage link https://sourceforge.net/projects/gmrun/ is [dead](https://repology.org/link/https://sourceforge.net/projects/gmrun/) (Connect timeout (60 seconds))
- Homepage link https://sourceforge.net/projects/id3lib/ is [dead](https://repology.org/link/https://sourceforge.net/projects/id3lib/) (Connect timeout (60 seconds))

There are several more.  It seems like a systematic issue.

**Comment by AMDmi3** [comment]
Systematic issue on sourceforge (or, rather, cloudflare) side, may be. Link checker is working as expected.
I've triggered recheck for timeout statuses for `*sourceforge*` urls, so some may be fixed soon. Others still timeout and this is reproducible, for instance on freefall.freebsd.org.
